# Generated by Django 5.0.1 on 2026-01-11 04:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '大模型类型',
                'verbose_name_plural': '大模型类型',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模型名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本号')),
                ('description', models.TextField(verbose_name='模型描述')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parameters_count', models.BigIntegerField(help_text='模型参数数量', verbose_name='参数量（整数）')),
                ('accuracy_score', models.DecimalField(decimal_places=2, help_text='0-100之间的准确率分数', max_digits=5, verbose_name='准确率（小数）')),
                ('training_hours', models.IntegerField(verbose_name='训练时长（小时）')),
                ('is_open_source', models.BooleanField(default=False, verbose_name='是否开源')),
                ('is_commercial', models.BooleanField(default=False, verbose_name='是否商用')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('contact_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='请输入有效的电子邮件地址')], verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效的中国大陆手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='联系电话')),
                ('developer', models.CharField(max_length=200, verbose_name='开发者/组织')),
                ('website_url', models.URLField(blank=True, verbose_name='官网地址')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='ai_models.modeltype', verbose_name='模型类型')),
            ],
            options={
                'verbose_name': 'AI大模型',
                'verbose_name_plural': 'AI大模型',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='ai_models_a_name_904e35_idx'), models.Index(fields=['model_type'], name='ai_models_a_model_t_00b493_idx')],
            },
        ),
    ]
